export const questionData = [
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question: "The Spitfire L.F. Mk IX had what engine?",
    correct_answer: "Merlin 66",
    incorrect_answers: ["Griffon 65", "Merlin 50", "Merlin X"],
  },
  {
    category: "Entertainment: Video Games",
    type: "boolean",
    difficulty: "medium",
    question:
      "DragonForce&#039;s &#039;Through the Fire and Flames&#039; is widely considered to be the hardest song in the Guitar Hero series.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "Geography",
    type: "boolean",
    difficulty: "easy",
    question: "Greenland is covered with grass and Iceland covered with ice.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question:
      "The following Spanish provinces are located in the northern area of Spain except:",
    correct_answer: "Murcia",
    incorrect_answers: ["Asturias", "Navarre", "Le&oacute;n"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "easy",
    question:
      "This Greek goddess&#039;s name was chosen for the dwarf planet responsible for discord on Pluto&#039;s classification amongst astronomers.",
    correct_answer: "Eris",
    incorrect_answers: ["Charon", "Ceres", "Dysnomia"],
  },
  {
    category: "Geography",
    type: "boolean",
    difficulty: "easy",
    question: "Alaska is the largest state in the United States.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "easy",
    question: "Nutella is produced by the German company Ferrero.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "hard",
    question:
      "Why was the character Trevor Philips discharged from the Air Force?",
    correct_answer: "Mental Health Issues",
    incorrect_answers: ["Injuries", "Disease", "Danger to Others"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "hard",
    question:
      "Which of these artists did NOT remix the song &quot;Faded&quot; by Alan Walker?",
    correct_answer: "Skrillex",
    incorrect_answers: ["Ti&euml;sto", "Slushii", "Dash Berlin"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "medium",
    question: "Who is the lead singer of Silverchair?",
    correct_answer: "Daniel Johns",
    incorrect_answers: ["Ben Gillies", "Chris Joannou", "George Costanza"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question: "Which of these &quot;Worms&quot; games featured 3D gameplay?",
    correct_answer: "Worms 4: Mayhem",
    incorrect_answers: [
      "Worms W.M.D",
      "Worms Reloaded",
      "Worms: Open Warfare 2",
    ],
  },
  {
    category: "Celebrities",
    type: "multiple",
    difficulty: "medium",
    question:
      "What year did radio icon Howard Stern start a job at radio station WNBC?",
    correct_answer: "1982",
    incorrect_answers: ["1985", "1984", "1995"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question: "What is the largest lake in the African continent?",
    correct_answer: "Lake Victoria",
    incorrect_answers: ["Lake Tanganyika", "Lake Malawi", "Lake Turkana"],
  },
  {
    category: "General Knowledge",
    type: "boolean",
    difficulty: "easy",
    question: "The color orange is named after the fruit.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "easy",
    question: "When was Minecraft first released to the public?",
    correct_answer: "May 17th, 2009",
    incorrect_answers: [
      "September 17th, 2009",
      "November 18th, 2011",
      "October 7th, 2011",
    ],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "medium",
    question:
      "Which one of these actors is said to be cut from the film &#039;E.T. the Extra-Terrestrial&#039;?",
    correct_answer: "Harrison Ford",
    incorrect_answers: [
      "Michael J. Fox",
      "Andy Kaufman",
      "Arnold Schwarzenegger",
    ],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question:
      "In &quot;Overwatch&quot;, what is the name of Mercy&#039;s &quot;ultimate ability&quot;?",
    correct_answer: "Valkyrie",
    incorrect_answers: ["Earthshatter", "Rocket Barrage", "Molten Core"],
  },
  {
    category: "Science & Nature",
    type: "multiple",
    difficulty: "hard",
    question:
      "Which of the following plastic is commonly used for window frames, gutters and drain pipes?",
    correct_answer: "Polyvinylchloride (PVC) ",
    incorrect_answers: [
      "Polyethylene (PE)",
      "Polypropylene (PP)",
      "Polystyrene (PS)",
    ],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "hard",
    question: "The key of sharps does the key of G# minor contain?",
    correct_answer: "5",
    incorrect_answers: ["3", "7", "0"],
  },
  {
    category: "Animals",
    type: "multiple",
    difficulty: "easy",
    question: "What is Grumpy Cat&#039;s real name?",
    correct_answer: "Tardar Sauce",
    incorrect_answers: ["Sauce", "Minnie", "Broccoli"],
  },
  {
    category: "Mythology",
    type: "multiple",
    difficulty: "hard",
    question: "Which of the following is NOT a god in Norse Mythology.",
    correct_answer: "Jens",
    incorrect_answers: ["Loki", "Tyr", "Snotra"],
  },
  {
    category: "Vehicles",
    type: "boolean",
    difficulty: "medium",
    question: "Ferrari has never made a V10 engine for any of its cars.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "Celebrities",
    type: "multiple",
    difficulty: "easy",
    question: "Which celebrity announced his presidency in 2015?",
    correct_answer: "Kanye West",
    incorrect_answers: ["Donald Trump", "Leonardo DiCaprio", "Miley Cyrus"],
  },
  {
    category: "Celebrities",
    type: "multiple",
    difficulty: "easy",
    question: "Aubrey Graham is better known as",
    correct_answer: "Drake",
    incorrect_answers: ["Travis Scott", "Lil Wayne", "2 Chainz"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question:
      "The New York Times slogan is, &ldquo;All the News That&rsquo;s Fit to&hellip;&rdquo;",
    correct_answer: "Print",
    incorrect_answers: ["Digest", "Look", "Read"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "medium",
    question:
      "What year did the James Cameron film &quot;Titanic&quot; come out in theaters?",
    correct_answer: "1997",
    incorrect_answers: ["1996", "1998", "1999"],
  },
  {
    category: "Entertainment: Japanese Anime & Manga",
    type: "boolean",
    difficulty: "hard",
    question: "Druid is a mage class in &quot;Log Horizon&quot;.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "hard",
    question:
      "In &quot;Starbound&quot;, what is the max HP of the monster &quot;Punchy&quot;?",
    correct_answer: "50,000 HP",
    incorrect_answers: ["9,000,000 HP", "100 HP", "150,000 HP"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "Who invented Pastafarianism?",
    correct_answer: "Bobby Henderson",
    incorrect_answers: ["Eric Tignor", "Bill Nye", "Zach Soldi"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "medium",
    question:
      "From which album is the Gorillaz song, &quot;On Melancholy Hill&quot; featured in?",
    correct_answer: "Plastic Beach",
    incorrect_answers: ["Demon Days", "Humanz", "The Fall"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "hard",
    question:
      "What is the name of the main island in PLAYERUNKNOWN&#039;S BATTLEGROUNDS?",
    correct_answer: "Erangel",
    incorrect_answers: ["Marmara", "Severny", "Lastovo"],
  },
  {
    category: "Entertainment: Books",
    type: "multiple",
    difficulty: "medium",
    question:
      "Which of the following was the author of &quot;Username Evie&quot;?",
    correct_answer: "Joe Sugg",
    incorrect_answers: ["Zoe Sugg", "Joe Weller", "Alfie Deyes"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question: "What is the capital city of Slovenia?",
    correct_answer: "Ljubljana",
    incorrect_answers: ["Maribor", "Velenje", "Trbovlje"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "easy",
    question: "Which band recorded the album &quot;Parallel Lines&quot;?",
    correct_answer: "Blondie",
    incorrect_answers: ["Paramore", "Coldplay", "The Police"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "medium",
    question: "Which of the following is the longest river in Europe?",
    correct_answer: "Volga",
    incorrect_answers: ["Danube", "Ural", "Dnieper"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the City in Saints Row The Third?",
    correct_answer: "Steelport",
    incorrect_answers: ["Stilwater", "Carcer", "Liberty"],
  },
  {
    category: "Art",
    type: "multiple",
    difficulty: "easy",
    question: "Who painted The Starry Night?",
    correct_answer: "Vincent van Gogh",
    incorrect_answers: ["Pablo Picasso", "Leonardo da Vinci", "Michelangelo"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "easy",
    question: "Which of the following is NOT a Nintendo game console?",
    correct_answer: "Dreamcast",
    incorrect_answers: ["SNES", "Wii", "Switch"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "easy",
    question:
      "Which of the following Pokemon Types was present in the original games, Red and Blue?",
    correct_answer: "Ice",
    incorrect_answers: ["Steel", "Dark", "Fairy"],
  },
  {
    category: "Entertainment: Music",
    type: "boolean",
    difficulty: "easy",
    question:
      "In 1993, Prince changed his name to an unpronounceable symbol because he was unhappy with his contract with Warner Bros.",
    correct_answer: "True",
    incorrect_answers: ["False"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "easy",
    question: "Which music publication is often abbreviated to NME?",
    correct_answer: "New Musical Express",
    incorrect_answers: [
      "New Metro Entertainment",
      "Next Musical Enterprise",
      "North Manchester Express",
    ],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "medium",
    question:
      "Which song made by MAN WITH A MISSION was used as the opening for the anime &quot;Log Horizon&quot;?",
    correct_answer: "&quot;Database&quot;",
    incorrect_answers: [
      "&quot;Dead End in Tokyo&quot;",
      "&quot;Raise Your Flag&quot;",
      "&quot;Out of Control&quot;",
    ],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "hard",
    question: "In Left 4 Dead, what is the character Bill&#039;s last name?",
    correct_answer: "Overbeck",
    incorrect_answers: ["Fish", "Roberts", "Stevenson"],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "hard",
    question:
      "Which of these is not a layer in the OSI model for data communications?",
    correct_answer: "Connection Layer",
    incorrect_answers: [
      "Application Layer",
      "Transport Layer",
      "Physical Layer",
    ],
  },
  {
    category: "Entertainment: Musicals & Theatres",
    type: "multiple",
    difficulty: "medium",
    question:
      "Who played Marquis de Lafayette and Thomas Jefferson in the original Broadway run of Hamilton?",
    correct_answer: "Daveed Diggs",
    incorrect_answers: [
      "Lin-Manuel Miranda",
      "Javier Mu&ntilde;oz",
      "Wayne Brady",
    ],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "easy",
    question:
      "What was the name of the canceled projected by Blizzard Entertainment that would be later become Overwatch?",
    correct_answer: "Titan",
    incorrect_answers: ["Omnic", "Omega", "Ghost"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question: "Who is the main villain of Kirby&#039;s Return to Dreamland?",
    correct_answer: "Magolor",
    incorrect_answers: ["Landia", "King Dedede", "Queen Sectonia "],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question:
      "What is the lowest amount of max health you can have in Team Fortress 2?",
    correct_answer: "70",
    incorrect_answers: ["100", "50", "95"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "Who invented the first ever chocolate bar, in 1847?",
    correct_answer: "Joseph Fry",
    incorrect_answers: ["Andrew Johnson", "John Cadbury", "John Tyler"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question: "In the video game DOTA 2, which of these is NOT a hero?",
    correct_answer: "Dragon Champion",
    incorrect_answers: ["Dark Seer", "Keeper of the Light", "Mirana"],
  },
];
